### ISSUE TITLE
iOS: Expose other properties

### ISSUE THREAD

**Issue by Daxito** [NathanaelA/nativescript-keyboardshowing#1]
iOS:
Is it possible to add if the "Text Autocomplete" is visible as well? and some other properties like height?
So this is the issue, this plugin https://github.com/tjvantoll/nativescript-IQKeyboardManager works but when it opens the keyboard it hides the "Action Bar" as well, what if the user wants to go Back?, they cannot, so I cannot use that plugin, what I was thinking is to just change the size of the screen based on the size of the keyboard when visible making the Action Bar Always available...hope it makes sense.

**Comment by roblav96** [comment]
Here's an implementation that only listens to the keyboard and describes the keyboard dimensions:
```typescript
application.ios.addNotificationObserver(UIKeyboardWillChangeFrameNotification, function(notification: NSNotification) {
	let rect: CGRect = notification.userInfo.valueForKey(UIKeyboardFrameEndUserInfoKey).CGRectValue
	LifeService.getEmitter().emit('keyboard', { rect })
})
```

**Comment by hackerunet** [comment]
Do you guys know how can I access to UIKeyboardWillChangeFrameNotification to be able to fix this issue?
