### ISSUE TITLE
Not working for Android

### ISSUE THREAD

**Issue by Daxito** [NathanaelA/nativescript-keyboardshowing#2]
I have this GalaxyS5, Android 6.0.1, and it is not working, it is triggering the `OnGlobalLayoutListener` but these values are always the same:

rect.bottom = 1920
screenHeight= 1089
missingSize = -831

It does not matter if the keyboard is closing or opening.

iOS is working perfect!

Thank you!

**Comment by markhatchell** [comment]
The issue is most likely caused by the AndroidManifest not having `android:windowSoftInputMode="adjustResize"` set. I have just fixed the issue so that it should not require that setting anymore. About to do a PR.

**Comment by markhatchell** [comment]
Sorry, my changes only detects when it opens, not when it closes. I decided to move my buttons to the top of the view so as to not need to know when the keyboard opens. Might work on this some more later. Here is my fork if you want to have a go. https://github.com/markhatchell/nativescript-keyboardshowing

**Comment by Mahaboobbaig** [comment]
Hi, I am also facing same problem. This plugin is not working in Native script with angular.
Can you please tell me how to use this plugin in native script with angular
