### ISSUE TITLE
How to use code?

### ISSUE THREAD

**Issue by syraz37** [NathanaelA/nativescript-keyboardshowing#4]
Where do I place this piece of code? I am using angular with typescript. I want to handle keyboard event inside the angular component.

```
exports.onKeyboard = function (evt) {
    console.log("Keyboard is now", evt.showing ? 'showing' : 'hidden');
};
```

**Comment by NathanaelA** [comment]
@syraz37  - The above code is only for a non-angular application.   In Angular I'm not sure how you can get access to this callback at this point.
